### ISSUE TITLE
usage of this project

### ISSUE THREAD

**Issue by thenamelessthing** [usmcgeek/MECCGRemastered#1]
Hi, I just watched your MECCG Remastered project and it's a great job you did. Question of highlighting this one, Rezwits would be interested in using your project in its cardnum project (online deck building and online game). Would you accept that your remastered cards be used there? Authorizes us to use them for this purpose? Thank you again for your work, it is motivating to see that other people share the same passion. Join forces, make the game better!

**Comment by usmcgeek** [comment]
These are posted for anybody's use.  I haven't seen any indication that Rezwits would want to use these - but if he did, I would be fine with that.  I don't own these, I'm just typing them up in the new templates I created.
